uab-hello:
    path:       /hello
    defaults:   { _controller: 'SimpleSAML\Module\uab\Controller\HelloController::discovery' }

uab-multiauth-discovery:
    path:       /discovery
    defaults:   { _controller: 'SimpleSAML\Module\uab\Controller\MultiAuthDiscoController::discovery' }

uab-sp-assertionConsumerService:
    path:       /sp/saml2-acs.php/{sourceId}
    defaults:   { _controller: 'SimpleSAML\Module\uab\Controller\ServiceProvider::assertionConsumerService' }
uab-sp-singleLogoutService:
    path:       /sp/saml2-logout.php/{sourceId}
    defaults:   { _controller: 'SimpleSAML\Module\uab\Controller\ServiceProvider::singleLogoutService' }
    
uab-primary-auth-notice:
    path:       /primary-auth-notice
    defaults:   { _controller: 'SimpleSAML\Module\uab\Controller\UserMatchController::primaryAuthNotice' }
   
uab-primary-auth:
    path:       /primary-auth
    defaults:   { _controller: 'SimpleSAML\Module\uab\Controller\UserMatchController::primaryAuth' }
   
uab-primary-auth-completed:
    path:       /primary-auth-completed
    defaults:   { _controller: 'SimpleSAML\Module\uab\Controller\UserMatchController::primaryAuthCompleted' }

uab-primary-account-disabled-notice:
    path:       /primary-account-disabled
    defaults:   { _controller: 'SimpleSAML\Module\uab\Controller\UserMatchController::primaryAccountDisabledNotice' }
   
uab-loginuserpass:
    path:       /loginuserpass
    defaults:   { _controller: 'SimpleSAML\Module\uab\Controller\Login::loginuserpass' }
   
uab-accessibility:
    path:       
        en: /accessibility
        pt: /acessibilidade
    defaults:   { _controller: 'SimpleSAML\Module\uab\Controller\Accessibility::page' }