version: '3.7'

volumes:
  db_data:
  #fs_data:

secrets:
  db_pwd:
    file: ./.docker/secrets/db_pwd.txt
  db_root_pwd:
    file: ./.docker/secrets/db_root_pwd.txt

networks:
  site:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 10.124.2.1/30

services:
  project:
    env_file:
      - .env
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      PROJECT_FOLDER: ${PROJECT_FOLDER}
      PROJECT_TITLE: ${PROJECT_TITLE}
      PROJECT_ADMIN_USER: ${PROJECT_ADMIN_USER}
      PROJECT_ADMIN_PWD: ${PROJECT_ADMIN_PWD}
      PROJECT_ADMIN_EMAIL: ${PROJECT_ADMIN_EMAIL}
      MYSQL_HOST: localhost
      MYSQL_DATABASE: ${PROJECT_NAME}_db
      MYSQL_USER: ${PROJECT_NAME}_wp
      SIMPLESAMLPHP_VERSION: ${SIMPLESAMLPHP_VERSION}
      SIMPLESAMLPHP_BRANCH: ${SIMPLESAMLPHP_BRANCH}
      MYSQL_PASSWORD: /run/secrets/db_pwd
    user: root
    volumes:
      - .:${WWW_DIR}/${PROJECT_FOLDER}/modules/uab
      - ${WWW_DIR}/${PROJECT_FOLDER}/modules/uab/.docker
      - ./cert:${WWW_DIR}/${PROJECT_FOLDER}/cert
      - ./config/authsources.php.dist:${WWW_DIR}/${PROJECT_FOLDER}/config/authsources.php
      - ./config/config.php.dist:${WWW_DIR}/${PROJECT_FOLDER}/config/config.php
      - ./metadata/saml20-idp-remote.php.dist:${WWW_DIR}/${PROJECT_FOLDER}/metadata/saml20-idp-remote.php
      - type: bind
        source: ./.docker/www
        target: ${WORK_DIR}/mirror/www
        bind:
          propagation: shared
      #- fs_data:${WWW_DIR}:rw
      - db_data:/var/lib/mysql
    networks:
      site:
    ports:
      - "80:80"
      - "443:443"
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    image: ${PROJECT_FOLDER}:latest
    working_dir: ${WWW_DIR}/${PROJECT_FOLDER}/
    restart: unless-stopped
    privileged: true
    secrets:
      - db_pwd
    container_name: ${PROJECT_FOLDER}
